# Generated by Django 4.2.4 on 2023-08-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("pub_date", models.DateTimeField(auto_now_add=True)),
                ("number", models.TextField()),
                ("category", models.TextField()),
            ],
        ),
    ]
