# Generated by Django 2.2.9 on 2023-08-31 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='docbase.Category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
