# Generated by Django 4.2.4 on 2023-08-09 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("docbase", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование категории",
                        max_length=100,
                        verbose_name="Наименование категории",
                    ),
                ),
                (
                    "pub_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания категории"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="doc",
            options={
                "ordering": ["-pub_create"],
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
            },
        ),
        migrations.RemoveField(
            model_name="doc",
            name="pub_date",
        ),
        migrations.AddField(
            model_name="doc",
            name="pub_create",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания документа",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="doc",
            name="name",
            field=models.CharField(
                help_text="Введите наименование документа",
                max_length=100,
                verbose_name="Наименование документа",
            ),
        ),
        migrations.AlterField(
            model_name="doc",
            name="number",
            field=models.CharField(
                help_text="Введите номер документа",
                max_length=10,
                verbose_name="Номер документа",
            ),
        ),
        migrations.AlterField(
            model_name="doc",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doc",
                to="docbase.category",
                verbose_name="Категория",
            ),
        ),
    ]
