# Generated by Django 4.2.4 on 2023-08-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docbase", "0002_category_alter_doc_options_remove_doc_pub_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="counter",
            field=models.IntegerField(
                default=1,
                help_text="Введите номер для нового элемента данной категории",
                verbose_name="Индекс для нового документа",
            ),
        ),
    ]
