# Generated by Django 4.2.4 on 2023-08-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docbase", "0003_category_counter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["-pub_create"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AddField(
            model_name="doc",
            name="data_doc",
            field=models.DateTimeField(null=True, verbose_name="Дата документа"),
        ),
        migrations.AddField(
            model_name="doc",
            name="file_path",
            field=models.CharField(
                help_text="Укажите путь до файла документа",
                max_length=200,
                null=True,
                verbose_name="Путь до файла документа",
            ),
        ),
    ]
